{"content": {"suites": {"0": {"status": {"total_pass": 12, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_server_get_historical_2", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_server_get_historical_interval_1", "rerun": "0"}, "3": {"status": "FAIL", "message": "   assert 500 == 200\n    +  where 500 = <Response [500]>.status_code\n", "test_name": "test_server_get_historical_interval_2", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_server_get_historical_date_1", "rerun": "0"}, "5": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_date_2", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_server_get_historical_wrong_name", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_server_indexes", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_server_index_WIG30", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_server_index_companies_WIG30", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_server_index_SP500", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_server_index_companies_SP500", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_server_companies", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_robots_bankier", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_robots_investing", "rerun": "0"}, "15": {"status": "FAIL", "message": "       assert 404 == 200\n        +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_timetest", "rerun": "0"}}, "suite_name": "test.py"}, "1": {"suite_name": "time_test.py", "tests": {"0": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[1-50]", "rerun": "0"}, "1": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[2-50]", "rerun": "0"}, "2": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[3-50]", "rerun": "0"}, "3": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[4-50]", "rerun": "0"}, "4": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[5-50]", "rerun": "0"}, "5": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[6-50]", "rerun": "0"}, "6": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[7-50]", "rerun": "0"}, "7": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[8-50]", "rerun": "0"}, "8": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[9-50]", "rerun": "0"}, "9": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[10-50]", "rerun": "0"}, "10": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[11-50]", "rerun": "0"}, "11": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[12-50]", "rerun": "0"}, "12": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[13-50]", "rerun": "0"}, "13": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[14-50]", "rerun": "0"}, "14": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[15-50]", "rerun": "0"}, "15": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[16-50]", "rerun": "0"}, "16": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[17-50]", "rerun": "0"}, "17": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[18-50]", "rerun": "0"}, "18": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[19-50]", "rerun": "0"}, "19": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[20-50]", "rerun": "0"}, "20": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[21-50]", "rerun": "0"}, "21": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[22-50]", "rerun": "0"}, "22": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[23-50]", "rerun": "0"}, "23": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[24-50]", "rerun": "0"}, "24": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[25-50]", "rerun": "0"}, "25": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[26-50]", "rerun": "0"}, "26": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[27-50]", "rerun": "0"}, "27": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[28-50]", "rerun": "0"}, "28": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[29-50]", "rerun": "0"}, "29": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[30-50]", "rerun": "0"}, "30": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[31-50]", "rerun": "0"}, "31": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[32-50]", "rerun": "0"}, "32": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[33-50]", "rerun": "0"}, "33": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[34-50]", "rerun": "0"}, "34": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[35-50]", "rerun": "0"}, "35": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[36-50]", "rerun": "0"}, "36": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[37-50]", "rerun": "0"}, "37": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[38-50]", "rerun": "0"}, "38": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[39-50]", "rerun": "0"}, "39": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[40-50]", "rerun": "0"}, "40": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[41-50]", "rerun": "0"}, "41": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[42-50]", "rerun": "0"}, "42": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[43-50]", "rerun": "0"}, "43": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[44-50]", "rerun": "0"}, "44": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[45-50]", "rerun": "0"}, "45": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[46-50]", "rerun": "0"}, "46": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[47-50]", "rerun": "0"}, "47": {"status": "FAIL", "message": "   assert 404 == 200\n    +  where 404 = <Response [404]>.status_code\n", "test_name": "test_server_get_historical_1[48-50]", "rerun": "0"}, "48": {"status": "FAIL", "message": "           ConnectionResetError: [Errno 104] Connection reset by peer\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n       requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n", "test_name": "test_server_get_historical_1[49-50]", "rerun": "0"}, "49": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7bfee0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=Allegro (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7bfee0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=Allegro (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7bfee0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_1[50-50]", "rerun": "0"}, "50": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf918520>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf918520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf918520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[1-50]", "rerun": "0"}, "51": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf9300d0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf9300d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf9300d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[2-50]", "rerun": "0"}, "52": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7b03a0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7b03a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7b03a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[3-50]", "rerun": "0"}, "53": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7e5a30>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7e5a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7e5a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[4-50]", "rerun": "0"}, "54": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf65b940>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf65b940>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf65b940>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[5-50]", "rerun": "0"}, "55": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7bc130>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7bc130>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7bc130>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[6-50]", "rerun": "0"}, "56": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eafb10100>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafb10100>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafb10100>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[7-50]", "rerun": "0"}, "57": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eafac0550>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafac0550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafac0550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[8-50]", "rerun": "0"}, "58": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf65e1c0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf65e1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf65e1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[9-50]", "rerun": "0"}, "59": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf62c550>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf62c550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf62c550>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[10-50]", "rerun": "0"}, "60": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eafab61c0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafab61c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafab61c0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[11-50]", "rerun": "0"}, "61": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf77b8b0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf77b8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf77b8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[12-50]", "rerun": "0"}, "62": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf805250>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf805250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf805250>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[13-50]", "rerun": "0"}, "63": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf8309a0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf8309a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf8309a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[14-50]", "rerun": "0"}, "64": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf6ae160>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6ae160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6ae160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[15-50]", "rerun": "0"}, "65": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf69dc10>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf69dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf69dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[16-50]", "rerun": "0"}, "66": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eafab6280>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafab6280>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafab6280>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[17-50]", "rerun": "0"}, "67": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf77c940>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf77c940>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf77c940>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[18-50]", "rerun": "0"}, "68": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf6b7b50>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6b7b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6b7b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[19-50]", "rerun": "0"}, "69": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf85ca90>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf85ca90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf85ca90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[20-50]", "rerun": "0"}, "70": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7e5a30>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7e5a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7e5a30>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[21-50]", "rerun": "0"}, "71": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eafa85c70>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafa85c70>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafa85c70>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[22-50]", "rerun": "0"}, "72": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf49b220>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf49b220>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf49b220>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[23-50]", "rerun": "0"}, "73": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf41b5b0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf41b5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf41b5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[24-50]", "rerun": "0"}, "74": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf4c10d0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf4c10d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf4c10d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[25-50]", "rerun": "0"}, "75": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eafa8d9a0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafa8d9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eafa8d9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[26-50]", "rerun": "0"}, "76": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf94e970>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf94e970>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf94e970>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[27-50]", "rerun": "0"}, "77": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf3dd9d0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3dd9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3dd9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[28-50]", "rerun": "0"}, "78": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf953280>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf953280>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf953280>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[29-50]", "rerun": "0"}, "79": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf3c6520>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3c6520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3c6520>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[30-50]", "rerun": "0"}, "80": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf3d6040>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3d6040>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3d6040>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[31-50]", "rerun": "0"}, "81": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf88b3a0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf88b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf88b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[32-50]", "rerun": "0"}, "82": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf49d340>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf49d340>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf49d340>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[33-50]", "rerun": "0"}, "83": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf986160>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf986160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf986160>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[34-50]", "rerun": "0"}, "84": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf6c9e80>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6c9e80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6c9e80>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[35-50]", "rerun": "0"}, "85": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf298190>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf298190>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf298190>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[36-50]", "rerun": "0"}, "86": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf966b50>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf966b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf966b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[37-50]", "rerun": "0"}, "87": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf6fd760>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6fd760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf6fd760>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[38-50]", "rerun": "0"}, "88": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf805100>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf805100>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf805100>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[39-50]", "rerun": "0"}, "89": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf4283d0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf4283d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf4283d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[40-50]", "rerun": "0"}, "90": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf9ee1f0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf9ee1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf9ee1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[41-50]", "rerun": "0"}, "91": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf249490>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf249490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf249490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[42-50]", "rerun": "0"}, "92": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7f04f0>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7f04f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7f04f0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[43-50]", "rerun": "0"}, "93": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf428130>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf428130>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf428130>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[44-50]", "rerun": "0"}, "94": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7e5820>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7e5820>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7e5820>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[45-50]", "rerun": "0"}, "95": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf3e3340>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3e3340>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf3e3340>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[46-50]", "rerun": "0"}, "96": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf966a90>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf966a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf966a90>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[47-50]", "rerun": "0"}, "97": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf7b1b50>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7b1b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf7b1b50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[48-50]", "rerun": "0"}, "98": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf2d9430>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf2d9430>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf2d9430>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[49-50]", "rerun": "0"}, "99": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0eaf729d60>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf729d60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /historical_data?name=ALLEGRO (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eaf729d60>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_server_get_historical_2[50-50]", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 100, "total_error": 0}}}}, "date": "January 07, 2022", "start_time": 1641561140.4766698, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "12", "fail": "104", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "116"}